-- TimeDB PostgreSQL Schema
-- Only the series table lives here (in the public schema).
-- All values tables live in ClickHouse.

CREATE TABLE IF NOT EXISTS series (
  series_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  unit          text NOT NULL,
  labels        jsonb NOT NULL DEFAULT '{}',
  description   text,
  overlapping   boolean NOT NULL DEFAULT false,
  retention     text NOT NULL DEFAULT 'medium',
  inserted_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT series_identity_uniq UNIQUE (name, labels),
  CONSTRAINT series_name_not_empty CHECK (length(btrim(name)) > 0),
  CONSTRAINT valid_retention CHECK (retention IN ('short', 'medium', 'long'))
);

CREATE INDEX IF NOT EXISTS series_labels_gin_idx ON series USING GIN (labels);
