BEGIN;

-- ============================================================================
-- users_table
-- ----------------------------------------------------------------------------
-- Stores user accounts with API keys for authentication.
-- The email field is used to populate the changed_by field in values_table.
-- ============================================================================

CREATE TABLE IF NOT EXISTS users_table (
  -- Unique identifier for each user
  user_id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Tenant identifier for multi-tenant support
  -- Each user belongs to a specific tenant
  tenant_id     uuid NOT NULL,

  -- Email address (used for changed_by in values_table)
  -- Must be unique within a tenant (email + tenant_id combination)
  email         text NOT NULL,

  -- API key for authentication (must be unique and not null)
  -- Should be a secure random token generated by the admin
  api_key       text NOT NULL UNIQUE,

  -- Whether the user account is active
  -- Inactive users cannot authenticate
  is_active     boolean NOT NULL DEFAULT true,

  -- Timestamps
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  -- Ensure email is not empty
  CONSTRAINT email_not_empty
    CHECK (length(btrim(email)) > 0),

  -- Ensure api_key is not empty
  CONSTRAINT api_key_not_empty
    CHECK (length(btrim(api_key)) > 0),

  -- Ensure unique email per tenant (same email can exist in different tenants)
  CONSTRAINT users_email_tenant_unique
    UNIQUE (tenant_id, email)
);

-- Index for efficient lookup by api_key (most common query for authentication)
CREATE INDEX IF NOT EXISTS users_api_key_idx
  ON users_table (api_key)
  WHERE is_active = true;

-- Index for efficient lookup by email within a tenant
CREATE INDEX IF NOT EXISTS users_email_tenant_idx
  ON users_table (tenant_id, email);

-- Index for efficient lookup by tenant_id
CREATE INDEX IF NOT EXISTS users_tenant_id_idx
  ON users_table (tenant_id);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at on row updates
CREATE TRIGGER users_updated_at_trigger
  BEFORE UPDATE ON users_table
  FOR EACH ROW
  EXECUTE FUNCTION update_users_updated_at();

COMMIT;

