services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.1
    container_name: timedb_clickhouse
    restart: always
    environment:
      TZ: UTC
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./chdata:/var/lib/clickhouse
